<select
        {!!$data['selectedId']??''!!}
        {!!$data['selectAttr']??''!!}
        {!!$data['title']??''!!}
        {!!$data['field']??''!!}
        {!!$data['name']??''!!}
        {!!$data['relation']??''!!}
        {!!$data['class']??''!!}
>
    {!!$data['options']??''!!}
</select>