name: build

on:
  push:
    branches: [ "master" ]


jobs:



  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

#      - name: Set up node env
#        uses: actions/setup-node@v2.5.1
#        with:
#          node-version: 20
#          cache: npm
#
#      - name: Install dependencies
#        run: npm ci --prefer-offline --no-audit
#
#      - name: Generate
#        run: npm run build
#
#      - name: Upload artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: build-artifact
#          path: dist

      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_KEY }}
          script: "cd /var/www/vitexopt/data/www/vitexopt.ru && ./.scripts/deploy.sh"
