name: build

on:
  push:
    branches:
      - "master"
      - "dev"

jobs:
  build-deploy-js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run vbuild

      - name: Copy file via scp
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "public/build/*"
          target: ${{ secrets.BUILD_DEST }}

  deploy-php:
    name: deploy-php
    runs-on: ubuntu-latest
    environment: main < -- here

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ${{ secrets.SERVER_PATH }}
            git pull --all
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          args: "--ignore-platform-reqs --optimize-autoloader"