name: build

on:
  push:
    branches:
      - "master"
      - "dev"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: main < -- here

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
             cd ${{ secrets.SERVER_PATH }}
             git pull --all